# https://github.com/saveourtool/diktat/blob/master/diktat-rules/src/main/resources/diktat-analysis.yml
- name: DIKTAT_COMMON
  configuration:
    domainName: ru.pixnews.wasm
    testDirs: test
    disabledChapters: ""
    kotlinVersion: 1.9
    srcDirectories: "main"

- name: AVOID_NULL_CHECKS
  enabled: false

- name: BACKTICKS_PROHIBITED
  enabled: true
  ignoreAnnotated: [ Nested, ParameterizedTest ]

- name: CLASS_NAME_INCORRECT
  enabled: false

- name: CLASS_SHOULD_NOT_BE_ABSTRACT
  enabled: false

- name: COMMENT_WHITE_SPACE
  enabled: false

# Enabled in Detekt
- name: CONSTANT_UPPERCASE
  enabled: false

- name: CUSTOM_GETTERS_SETTERS
  enabled: false

# Enabled in Detekt
- name: EMPTY_BLOCK_STRUCTURE_ERROR
  enabled: false

- name: ENUMS_SEPARATED
  enabled: false

- name: EXTENSION_FUNCTION_WITH_CLASS
  enabled: false

# "MatchingDeclarationName" rule in Detekt
- name: FILE_NAME_MATCH_CLASS
  enabled: false

- name: FILE_NAME_INCORRECT
  enabled: false

- name: FILE_NO_BLANK_LINE_BETWEEN_BLOCKS
  enabled: true

#  Enabled in Detekt
- name: FILE_UNORDERED_IMPORTS
  enabled: false
  configuration:
    useRecommendedImportsOrder: false

#  Enabled in Detekt
- name: FILE_WILDCARD_IMPORTS
  enabled: false

- name: FLOAT_IN_ACCURATE_CALCULATIONS
  enabled: false

- name: FUNCTION_BOOLEAN_PREFIX
  enabled: false

- name: FUNCTION_NAME_INCORRECT_CASE
  enabled: false

- name: GENERIC_VARIABLE_WRONG_DECLARATION
  enabled: true
  ignoreAnnotated: [ Rule ]

- name: GENERIC_NAME
  enabled: false

- name: HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE
  enabled: false

- name: HEADER_MISSING_OR_WRONG_COPYRIGHT
  enabled: true
  configuration:
    isCopyrightMandatory: true
    copyrightText: 'Copyright ;@currYear;, the wasm-sqlite-open-helper project authors and contributors. Please see the AUTHORS file'

- name: HEADER_WRONG_FORMAT
  enabled: false

- name: IDENTIFIER_LENGTH
  ignoreAnnotated: [ Test ]

- name: KDOC_NO_CONSTRUCTOR_PROPERTY
  enabled: false

- name: KDOC_NO_EMPTY_TAGS
  enabled: false

- name: KDOC_WITHOUT_RETURN_TAG
  enabled: false

- name: KDOC_WITHOUT_PARAM_TAG
  enabled: false

# Enabled in Detekt
- name: LONG_LINE
  enabled: false

- name: LONG_NUMERICAL_VALUES_SEPARATED
  enabled: true
  configuration:
    maxNumberLength: '8'
    maxBlockLength: '4'

- name: LAMBDA_IS_NOT_LAST_PARAMETER
  enabled: true
  ignoreAnnotated: [ Composable ]

- name: MAGIC_NUMBER
  enabled: false

- name: MISSING_KDOC_CLASS_ELEMENTS
  enabled: false

- name: MISSING_KDOC_ON_FUNCTION
  enabled: false

- name: MISSING_KDOC_TOP_LEVEL
  enabled: false

- name: NESTED_BLOCK
  enabled: false

- name: PACKAGE_NAME_INCORRECT_PATH
  enabled: false

- name: RUN_IN_SCRIPT
  enabled: false

- name: SAY_NO_TO_VAR
  enabled: false

# Slow
- name: SMART_CAST_NEEDED
  enabled: false

- name: TOO_LONG_FUNCTION
  enabled: false

- name: TOO_MANY_PARAMETERS
  enabled: false

- name: TOP_LEVEL_ORDER
  enabled: false

# Enabled in Detekt
- name: TRAILING_COMMA
  enabled: false

- name: TYPE_ALIAS
  enabled: false

# Enabled in Detekt
- name: UNUSED_IMPORT
  enabled: false

- name: USE_DATA_CLASS
  enabled: false

- name: VARIABLE_HAS_PREFIX
  enabled: false

- name: VARIABLE_NAME_INCORRECT_FORMAT
  enabled: false

- name: WHEN_WITHOUT_ELSE
  enabled: false

- name: WRONG_INDENTATION
  enabled: false

- name: WRONG_NEWLINES
  enabled: false

- name: WRONG_NEWLINES_AROUND_KDOC
  enabled: false

# Clashes with "ArgumentListWrapping" and "Wrapping" from the Detekt rule set
- name: WRONG_WHITESPACE
  enabled: false
